import('./pages/projects/residential/na-kalinina-almaty-2022/na-kalinina-almaty-2022.html');
import('./pages/projects/residential/zhk-oscar-almaty-2022/zhk-oscar-almaty-2022.html');
import('./pages/projects/residential/zhk-atlant-almaty-2021/zhk-atlant-almaty-2021.html');
import('./pages/projects/residential/zhk-rams-city-almaty-2023/zhk-rams-city-almaty-2023.html');
import('./pages/projects/residential/zhk-khan-tengri-almaty-2023/zhk-khan-tengri-almaty-2023.html');
import('./pages/projects/commercial/cafe-vanilla-almaty-2023/cafe-vanilla-almaty-2023.html');
import('./pages/projects/commercial/kofejnya-momento-almaty-2023/kofejnya-momento-almaty-2023.html');
import('./modules/preloader/_preloader');
import('./modules/content-load/content-load');
import('./articles.scss')
import('./modules/scroll-to-top/_scroll-to-top');